--- 
title: "Produção do Conhecimento Científico"
author:
  - Elaine Christine de Magalhães Cabral Albuquerque
  - Rejane de Almeida Santana dos Santos
  - Simão Pedro de Oliveira Urpia
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: []
biblio-style: apalike
link-citations: yes
description: "E-book em desenvolvimento."
---

# Introdução {-}

Estudante, ao longo da nossa vida experimentamos, aprendemos, ensinamos e compartilhamos vivências. Você, provavelmente, já aprendeu muita coisa por aí com sua família, seus professores, amigos e conhecidos. Neste E-book, há momentos tanto para você compartilhar suas experiências e aprendizados quanto para fazer novas descobertas. Você irá levantar perguntas e testar hipóteses, resolver problemas, conhecer as causas e os efeitos de alguns fenômenos, compreender certos processos sociais e culturais, entre outros assuntos.

Este E-book é um dos três livros componentes do nosso **Projeto Ciências de Dados na Educação Pública** com os quais vocês aprenderam e integraram novos conhecimentos. Esperamos que aproveitem cada momento desse aprendizado!


Boas descobertas!
